#- name: clean yum cache
#  command: yum clean all

- name: Install EPEL repo
  yum:
   name: 
    - https://mirror.yandex.ru/epel/epel-release-latest-8.noarch.rpm
    - https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    - http://remi.mirror.ate.info/enterprise/remi-release-8.rpm
   state: present
   disable_gpg_check: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Add CentOS repo
  copy:
    src: CentOS-repo.repo
    dest: /etc/yum.repos.d/CentOS-repo.repo

- name: Install packets
  yum: 
   name: 
    - python3-pip
    - docker-ce
    - mc
    - git
    - curl
    - wget
    - nano
   state: latest
   disable_gpg_check: yes
  
- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install setuptools-rust
  pip:
   name:
    - setuptools-rust

- name: Install Docker-compose = 1.25.4
  pip: 
   name: 
    - docker-compose
   version: 1.25.4
   
- name: Set service Docker
  systemd:
    name: docker
    state: started
    enabled: True
