- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Add multiple repositories
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    
- name: Add Docker repo
  yum_repository:
    name: docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: no

- name: Install packets
  yum: 
   name: 
    - docker
    - mc
    - git
    - curl
    - wget
    - nano
   state: latest
   disable_gpg_check: yes
  become: yes
  
- name: Install Docker-compose = 1.25.4
  yum: 
   name: 
    - docker-compose-1.25.4
   state:
   
- name: Set service Docker
  systemd:
    name: docker
    state: started
    enabled: True
